### ISSUE TITLE
image2

### ISSUE THREAD

**Issue by ebeyabraham** [Poirot1729/Open-CV#2]
![ice_screenshot_20170202-151145](https://cloud.githubusercontent.com/assets/15849927/22544366/731ab996-e95a-11e6-9b00-adbc250764e6.png)

**Comment by gautamkrishnar** [comment]
Hello @Poirot1729 Please keep these types of issues closed. I recommend creating single issue for all the images... just add more images as the comment of the issue...
Please see this issue as an example: https://github.com/gautamkrishnar/socli/issues/1
