### ISSUE TITLE
Error in executing. Please do help me in this

### ISSUE THREAD

**Issue by saisuhas** [Poirot1729/Open-CV#6]
Traceback (most recent call last):
  File "C:/Users/Chaitanya/Desktop/major project/m.py", line 14, in <module>
    _,contours, hierarchy = cv2.findContours(thresh,1,1)
ValueError: need more than 2 values to unpack

**Comment by ebeyabraham** [comment]
You might be using OpenCV 2... in that findContours returns only two arguments. So just change that line to `contours, hierarchy = cv2.findContours(thresh,1,1)`
